[versions]
kotest = "5.7.2"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:1.9.10"

[libraries]
kotest-core = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
